### ISSUE TITLE
Change domain configuration

### ISSUE THREAD

**Issue by gabrielbdornas** [gabrielbdornas/code#12]
The site domain must be braico.me and note code.braico.me.

## Task list

- [x] Change domain to braico.me.
- [x] Remove `code` subdmain configuration.
- [x] Remove `www` subdmain configuration.
