### ISSUE TITLE
How to modify existing, unpushed commit messages?

### ISSUE THREAD

**Issue by gabrielbdornas** [gabrielbdornas/code#9]
This question appears after 5 or 6 commits not refering with `#` the issue #5.

[This Stackoverflow](https://stackoverflow.com/a/179147/11755155) answer was perfect.

I have, also, a note about it.

## Task List

- [ ] Find and relate my previews note here.
- [ ] Create a post about it.
- [ ] Make a video about it.
